//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.27 at 03:28:48 PM GST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "com/rish/tutorial/springboot/soap/server/xsd/models", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.rish.tutorial.springboot.soap.server.xsd.models;
